### ISSUE TITLE
Erro na geração do TOKEN - ERRO = System.NullReferenceException: 'Object reference not set to an instance of an object.'

### ISSUE THREAD

**Issue by MarteFilho** [balta-io/7194#2]
https://prnt.sc/t5t0jw
https://prnt.sc/t5t0jw

Código:

using CopaVale.Models;
using Microsoft.IdentityModel.Tokens;
using System;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;

namespace CopaVale.Service
{
    public static class TokenService
    {
        public static string GenerateToken(User user)
        {
            var tokenHandler = new JwtSecurityTokenHandler();
            var key = Encoding.ASCII.GetBytes(Settings.Secret);
            var tokenDescriptor = new SecurityTokenDescriptor
            {
                Subject = new ClaimsIdentity(new Claim[]
                {
                    new Claim(ClaimTypes.Name, user.Nickname.ToString()),
                    new Claim(ClaimTypes.Role, user.Role.ToString())
                }),

                Expires = DateTime.UtcNow.AddHours(2),
                SigningCredentials = new SigningCredentials(new SymmetricSecurityKey(key), SecurityAlgorithms.HmacSha256Signature)
            };

            var token = tokenHandler.CreateToken(tokenDescriptor);
            return tokenHandler.WriteToken(token);
        }
    }
}

------------------------------------------------------------------------------------------------------------------------------------------

Model User

using System.ComponentModel.DataAnnotations;

namespace CopaVale.Models
{
    public class User
    {
        public int Id { get; set; }

        [Required]
        [MinLength(3)]
        [MaxLength(50)]
        public string Name { get; set; }

        [Required]
        [MinLength(1)]
        [MaxLength(50)]
        public string Nickname { get; set; }

        [Required]
        [MinLength(5)]
        [MaxLength(50)]
        public string Email { get; set; }

        [Required]
        [MinLength(5)]
        [MaxLength(50)]
        public string Password { get; set; }

        [Required]
        [MinLength(10)]
        [MaxLength(50)]
        public string FaceitURL { get; set; }

        [MinLength(10)]
        [MaxLength(10)]
        public string Role { get; set; }

    }
}

------------------------------------------------------------------------------------------------------------------------------
Post

{
"nickname": "Marcola",
"password": "123456"
}

Response:

{
    "erro": "Não foi possível se conectar com o banco de dados para a criação do usuário!"
}

**Comment by andrebaltieri** [comment]
@MarteFilho por favor, descreve com mais carinho o que precisa, o erro que ocorre, quando ocorre...
Se vou desprender um tempo te ajudando, então preciso do seu empenho em me dizer como te ajudar por favor!

**Comment by MarteFilho** [comment]
Erro ao tentar fazer a autenticação do usuário e gerar o token: 
System.NullReferenceException: 'Object reference not set to an instance of an object.'

**Comment by MarteFilho** [comment]
Segue detalhes do erro:

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=CopaVale
  StackTrace:
   at CopaVale.Service.TokenService.GenerateToken(User user) in C:\Users\marco\source\repos\CopaVale-Api\Service\TokenService.cs:line 16

**Comment by MarteFilho** [comment]
Startup.cs: ----------------------

using CopaVale.Context;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.IdentityModel.Tokens;
using System.Text;

namespace CopaVale
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContext<DataContext>(opt => opt.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
            services.AddControllers();

            var key = Encoding.ASCII.GetBytes(Settings.Secret);

            services.AddAuthentication(x =>
            {
                x.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                x.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
            }
            ).AddJwtBearer(x =>
            {
                x.RequireHttpsMetadata = false;
                x.SaveToken = true;
                x.TokenValidationParameters = new TokenValidationParameters
                {
                    ValidateIssuerSigningKey = true,
                    IssuerSigningKey = new SymmetricSecurityKey(key),
                    ValidateIssuer = false,
                    ValidateAudience = false,
                };
            });

        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {



            app.UseDeveloperExceptionPage();


            app.UseHttpsRedirection();
            app.UseRouting();
            app.UseCors(x =>
            x.AllowAnyOrigin().AllowAnyMethod().AllowAnyHeader());

            

            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }
    }
}

**Comment by andrebaltieri** [comment]
@MarteFilho por favor, debuga a aplicação e manda um print do valor que está recebendo no objeto `user` no método `GenerateToken` da classe `TokenService`.

Caso precise de ajuda para depurar a aplicação no Visual Studio Code, nos primeiros minutos deste vídeo eu mostro:
https://youtu.be/giCR4VgKjQY

**Comment by MarteFilho** [comment]
Problema Resolvido! Erro: o Role do usuário estava vindo como NULL

**Comment by MarteFilho** [comment]
Resolução: Criação de um outro usuário com o role "usuário".
